id: PBBB8A87E
initial_creation_type: input
source_metadata:
  title: Praise Series
  language: bo
  description: 'A selection of praises (Skt. stotra; Tib. bstod pa) to various Buddhist
    deities and prominent masters (arranged according to subject):'
  volume:
    2096a57299b540f4be849843e3600c77:
      title: Verses of Homage to the Buddhas and Bodhisattvas Together with their
        Mantras
      parent: General
    aa27c74cbcb441fe8bb3388a42f6c0fd:
      title: 'The Sun that Causes the Lotus of Intelligence to Bloom: In Praise of
        the Lineage of Gurus for the Noble Abhidharma'
      parent: Abhidharma Lineage
    60ca66723f9747d0b845d4b8f383df41:
      title: Verses in Praise of the Protector Akṣobhya
      parent: Akṣobhya
    a3b8ac61569743a2915fa68f071f8750:
      title: Praise of Noble Avalokiteśvara
      parent: Avalokiteśvara
    7616f98ac743403caacfa1c2ae2b62fd:
      title: Praise of Noble Avalokiteśvara (Tengyur version)
      parent: Avalokiteśvara
    0b1742bd9a7e49a9910f6c38b609cf37:
      title: Short Praise of the Buddha's Deeds
      parent: Buddha Śākyamuni
    a5795296a61f404fa18a29e2d89abd8c:
      title: Praise of the Twelve Acts of the Buddha
      parent: Buddha Śākyamuni
    b87a38adf71742ac94a2bc258c8fe3c7:
      title: In Praise of the Twelve Deeds of the Buddha
      parent: Buddha Śākyamuni
    7ed301fb6da9463da0d1c4478fcbd166:
      title: 'Praise of the Buddha: With Skilful Means & Compassion...'
      parent: Buddha Śākyamuni
    e4e7a7946f8a4ea38f0e8b1e1b60862a:
      title: 'Introduction to the Buddha’s Words: A Praise and Aspiration Related
        to the Words of the Victorious One'
      parent: Buddha's Words
    f10e98ddfcbf419f84e252b2a5667433:
      title: 'A Beautiful Lotus Garland: In Praise of the Omniscient Lord of Dharma
        Butön Rinchen Drup'
      parent: Butön Rinchen Drup
    569f36d637aa41869a0cb6808601e80a:
      title: 'The Swift Infusion of Blessings: In Praise of the Mahāpaṇḍita Candragomin'
      parent: Candragomin
    24f3b2f825cc4c24ae9c4c59a2fee936:
      title: 'The Melodious Song of Joy: In Praise of the Master Candrakīrti'
      parent: Candrakīrti
    01f6ce2e704746b9b75a2bf144dc2ac0:
      title: Praise of Candrakīrti
      parent: Candrakīrti
    8134eaecbf74411abad9edadab5a76c4:
      title: 'The Excellent Bilva Tree of Auspiciousness: Praise and Prayer to Terchen
        Chokgyur Lingpa'
      parent: Chokgyur Dechen Lingpa
    30711ed6517a4bc9a32ae8bc4db1a67a:
      title: A Homage to His Holiness the Dalai Lama
      parent: Fourteenth Dalai Lama
    3a6ff6d3cd974b0daf7714fe6d9318f0:
      title: Verses of Homage
      parent: Fourteenth Dalai Lama
    26888f787412429a9b42d8d45b0ce833:
      title: Praise of Kunga Yeshe, Great Being and Master of Extensive Scriptural
        Traditions
      parent: Ga Rabjampa Kunga Yeshe
    e0a22756d5ce43baa86fdeea73ecf04d:
      title: 'Cloud Banks of Blessings: Praise and Prayer to the Vajradhara Ngawang
        Lekpa'
      parent: Gatön Ngawang Lekpa
    1859ec40a49948cea31a17cf056ae98a:
      title: 'Thunderous Melody: In Praise of the Omniscient Gorampa Sonam Senge'
      parent: Gorampa Sonam Senge
    b6280e2267cb443aa9f98f7fb2357157:
      title: In Praise of Padmākara, the Great Guru of Uḍḍiyāna
      parent: Guru Padmasambhava
    94fa331bcbc049c891e093a2a93919b6:
      title: 'The Three Kāyas: Praises to the Great Master Padmasambhava'
      parent: Guru Padmasambhava
    f342585a8c82477eb96d1a347e2fd37b:
      title: A Praise to the Lotus King
      parent: Guru Padmasambhava
    27c2203c77284a6a8f8130290a37e0a7:
      title: 'Fully Blossomed Learning and Contemplation: A Praise of the Great Spiritual
        Friend Jamyang Gyaltsen'
      parent: Jamyang Gyaltsen
    0e49ec895e4a4547bd196b7986dbec74:
      title: In Praise of Jamyang Khyentse Wangpo
      parent: Jamyang Khyentse Wangpo
    40699a98fae742bd933f653170cb2e27:
      title: 'The Bestowal of Supreme Blessings: Praise to the Vajradhara Loter Wangpo'
      parent: Jamyang Loter Wangpo
    69460bf88a3540ba93f4df3b38dba33a:
      title: In Praise of Jigme Lingpa’s Pre-Eminence
      parent: Jigme Lingpa
    e9d802bc037447929da559b09ce633be:
      title: 'Sweet Melody to Delight the Glorious Deity: In Praise of Śrī Kālīdevī'
      parent: Kālīdevī
    b47458e81af042ac8ada110e3e11d623:
      title: 'Beautiful Adornment of the Earth: In Praise of Kṣitigarbha'
      parent: Kṣitigarbha
    10cd08b81bff49bab605eff485bbb776:
      title: In Praise of Longchenpa – The Greatness of the Omniscient Longchen Rabjam
      parent: Longchen Rabjam
    978bbe494dd044379c5572a6214e0b11:
      title: In Praise of the Lords of the Three Families
      parent: Lords of the Three Families
    387917da58f54c6cbfa8ba8bf2d29bd3:
      title: 'Cutting through the Four Demons in Absolute Space: A Praise of Machik
        Labdrön'
      parent: Machik Labdrön
    a6f757ba678a4ebc9eb1160a93fc81aa:
      title: 'Music to Delight the Ḍākinī: A Praise to the Deathless Mandāravā'
      parent: Mandāravā
    91116bf4b3f24b4c9bd72deba599b889:
      title: 'The Fresh Saffron Flower: In Praise of Venerable Mañjughoṣa'
      parent: Mañjuśrī
    8d5869be9e704def97c2ab9c1fb67712:
      title: 'The Light of Wisdom: Praise to Mañjuśrī'
      parent: Mañjuśrī
    11f3aadc9ed04248a8d98dc9eae3a705:
      title: 'The Lute of Vajra Harmony: Praise to the Protector Mañjuśrī'
      parent: Mañjuśrī
    6ea3644b07304118affd7def33940452:
      title: 'The Swift Infusion of Blessings: In Praise of Mañjughoṣa'
      parent: Mañjuśrī
    8ca0dc2416db4854a0bb3cd7472357dc:
      title: 'In Praise of Mañjuśrī: Increasing Intelligence to the Full'
      parent: Mañjuśrī
    aa42214543564c0fa6ba1b4b2234df59:
      title: 'In Praise of Mañjuśrī: The Great Treasure of Blessings'
      parent: Mañjuśrī
    dae887d19f2045a293d6d36d759788bc:
      title: In Praise of the Protector Mañjughoṣa
      parent: Mañjuśrī
    d65532e5ae8e4bb9bf42887ad6f8d3aa:
      title: Ultimate Praise of the Noble and Venerable Mañjuśrī
      parent: Mañjuśrī
    4def292489044658a310a15c30d1ce76:
      title: Praise to Mañjughoṣa
      parent: Mañjuśrī
    1dc38034eb0d4b2db656ce6c0794392a:
      title: The Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
      parent: Mañjuśrī
    8be23b9793c24663ae98676612f54068:
      title: In Praise of the Goddess Mārīcī (Özerchenma)
      parent: Mārīcī
    5092501957e34594ad7d7b07a7d033e3:
      title: In Praise of Jetsün Mila Shepa Dorje
      parent: Milarepa
    eec67a5e00844eceb4f8c337a2d42c50:
      title: 'The Definitive Ascertainment of Tantra: In Praise of the Great Master
        Milarepa'
      parent: Milarepa
    6d3713f8e81348158e8325220b238447:
      title: Homage to Milarepa
      parent: Milarepa
    20c8ec518664410289e69b45b862821f:
      title: 'The Purifier of Ethical Discipline: An Aspirational Praise to Vajradhara
        Kunga Zangpo'
      parent: Ngorchen Kunga Zangpo
    5e7dccc65bdb4300be713ce70fd506e0:
      title: In Praise of Patrul Orgyen Jigme Chökyi Wangpo
      parent: Patrul Rinpoche
    ff11d30da03145ae85d0e98818fbe70a:
      title: In Praise of Sönam Palge
      parent: Rogza Sönam Palge
    4830ee90dbaa44e8baa3fce49fce470f:
      title: A Short Guide to Yangleshö in Nepal
      parent: Sacred Places
    4acb164aa23c426da4c4b42c6336d2c2:
      title: 'A Song of Perfect Joy: In Praise of the Sacred Sites of Rājgṛha, Vulture
        Peak and Nālandā'
      parent: Sacred Places
    0bc6825c7438426f8596a71befe27200:
      title: In Praise of Devāvatāra, Site of Buddha's Descent from Heaven
      parent: Sacred Places
    642958370b914a16b1574b6c0bbc39ad:
      title: In Praise of Kuśinagara
      parent: Sacred Places
    c1c08e61a73a48e3ad47e6e2e3bb67e2:
      title: In Praise of Vārāṇasī, the Supreme Place
      parent: Sacred Places
    0e1467983057416bade415fc13bebc88:
      title: In Praise of Yangleshö in Nepal
      parent: Sacred Places
    37c5203c11c046419a7134039dd77085:
      title: In Praise of the Great Indian City of Kolkata
      parent: Sacred Places
    82cf88125d734cc4b47de728bfe4b74e:
      title: Offering Clouds to Delight the Victorious Ones, Combining A Praise of
        Redreng with a Prayer of Aspiration
      parent: Sacred Places
    3ff614f62d3645b9a6e01365c1df725b:
      title: Praise and Prayer to Kharchu, Great Sacred Place of Lhodrak
      parent: Sacred Places
    1b04e6d3fa234b61882c6d05eac2e9fe:
      title: 'The Conquerors'' Delight: In Praise of Śrāvastī'
      parent: Sacred Places
    e2f47844776d45d0a910e06e67b4fafc:
      title: 'The White Lotus Garland of Immortality: In Praise of the Supreme Vajra
        Place, Tso Pema (Lotus Lake)'
      parent: Sacred Places
    f60edce8a5524d72b142d5abb2fba3cf:
      title: 'The White Lotus: In Praise of Lumbinī'
      parent: Sacred Places
    7e6e0356f09c421d979a7de3cfce7a60:
      title: 'Melodious Sound: In Praise of Vulture Peak Mountain'
      parent: Sacred Places
    cbebc3cbdd0e459cbbe24104a74921b0:
      title: Praise to Sakya Paṇḍita
      parent: Sakya Paṇḍita
    20f5a9c623964fd38a96e84a9967e95a:
      title: 'Gentle Splendour: Praises to the Great Abbot Śāntarakṣita'
      parent: Śāntarakṣita
    83b774f84ac244ebb7f7f25a50a130f1:
      title: 'Ripples on the Ganges: In Praise of the Goddess Sarasvatī'
      parent: Sarasvatī
    2ce5a68a849d410ba7df64c99ec6408f:
      title: 'The Melodious Song of Vajra Harmony: In Praise of Red Sarasvatī'
      parent: Sarasvatī
    889d658a662f43d1a48be75fac8e6802:
      title: 'The Sweet Sound of Perfect Joy: In Praise of the Goddess Sarasvatī'
      parent: Sarasvatī
    6fff312367954183b16988cbafc59d8f:
      title: 'Intensely Brilliant Wisdom: In Praise of the Great Elder Smṛtijñāna'
      parent: Smṛtijñānakīrti
    6b59769fb7324ffa9ed8936043208ab5:
      title: The Praise to Tārā with Twenty-One Verses of Homage and The Excellent
        Benefits of Reciting the Praise
      parent: Tārā
    25e02876b34c46829e840528bec08cce:
      title: 'The Fulfilment of All Aspirations: In Praise of Noble Tārā'
      parent: Tārā
    41ac955d02fb4f5bbf518f83e236a2ad:
      title: 'Flower of Faith: In Praise of Tāranātha, Lord of Secrets'
      parent: Tāranātha
    732e87c5b8ee4e53b92a369f2ea5530b:
      title: 'A Blossoming of the Intellect: In Praise of the Great Pioneer Thönmi
        Sambhoṭa'
      parent: Thönmi Sambhoṭa
    77f2e5c9502d4a0689fa1641e78fe32f:
      title: In Praise of the Three Jewels
      parent: Three Jewels
    cab230e8db39472d91a990171e1e5be9:
      title: 'Snowy Lands: Praises to the Great Dharma Emperor Tri Songdetsen'
      parent: Tri Songdetsen
    82dc4ff90a054e338ec66d6e5535669d:
      title: 'The Flower of Faith: Praise to the Great Lord Guru Tsongkhapa'
      parent: Tsongkhapa Lobzang Drakpa
    fe3d44ec45af4b3595bf8d56aee1e223:
      title: A Song of Innermost Praise to Vajrasattva
      parent: Vajrasattva
    0e096454b1c8419494bcb20623676294:
      title: 'Wish-Granting Provision of Twofold Accomplishment: A Praise of Vajrasattva'
      parent: Vajrasattva
    a5d836cf8b604608a6073b991cb37b12:
      title: In Praise of Glorious Vajrasattva
      parent: Vajrasattva
    9bbeb00e05b445e28fa8c97a0129a0b0:
      title: 'The Staircase Ascending to Khecara: A Praise in Accord with the Arrangement
        of the Realm of Holy Nāro Khecarī'
      parent: Vajrayoginī
    25561a84305f40fb9ee9ac29ca7abad9:
      title: 'The Hero''s Bellowing Laughter: In Praise of the Lord of Yogins'
      parent: Virūpa
created_at: '2022-03-01T05:11:17.808661'
last_modified_at: '2022-03-01T05:11:17.808663'
